# This is a basic workflow to help you get started with Actions

name: Azure Container Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ main ] 
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: 'Build Test Image'
      run: |
        docker build . -t ghcr.io/kafekhalife/kafekhalife-test:{{ github.sha }}
        docker push ghcr.io/kafekhalife/kafekhalife-test:{{ github.sha }}

    - uses: azure/docker-login@v1
      with:
        login-server: ghcr.io
        username: skhalife
        password: ${{ secrets.CR_PAT }}
        
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'kafekhalife'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'ghcr.io/kafekhalife/kafekhalife-test:{{ github.sha }}'
