on:
    push: 
        
    # Publish `v1.2.3` tags as releases.
        tags:
         - v*
     
env: 
    IMG_URL: ghcr.io/kafekhalife/kafekhalife
    IMG_VERSION: ${{ github.ref }} 

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@master
      
      - uses: Azure/docker-login@v1
        with:
          login-server: ghcr.io
          username: ${{ secrets.CR_USR }}
          password: ${{ secrets.CR_PAT }}
      
      - run: |
          echo IMAGE=$IMG_URL:$IMG_VERSION
          docker build . -t $IMG_URL:$IMG_VERSION
          docker push $IMG_URL:$IMG_VERSION
        
      # Set the target AKS cluster.
      - uses: Azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_K8S_CREDS }}'
          cluster-name: sk-gh-talk
          resource-group: k8s-testing
          
      - uses: Azure/k8s-create-secret@v1
        with:
          container-registry-url: ghcr.io
          container-registry-username: ${{ secrets.CR_USR }}
          container-registry-password: ${{ secrets.CR_PAT }}
          secret-name: demo-k8s-secret
  
      - uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            manifests/deployment.yml
          images: |
            $IMG_URL:$IMG_VERSION
          imagepullsecrets: |
            demo-k8s-secret
